// Native gameplay tags. Content-specific tags (enemy families, items ...) live in data/ini files.
#pragma once

#include "NativeGameplayTags.h"

namespace DBTags
{
	// Input
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LightAttack);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_HeavyAttack);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LockOn);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability1);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability2);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability3);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability4);

	// Character state
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ParryWindow);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);

	// Damage
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Physical);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Fire);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Frost);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Lightning);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Shadow);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Poison);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Spirit);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_DarkBlood);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Unblockable);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Unparryable);

	// Classes
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Warrior);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Shadowrunner);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Mage);
	DARKBLOOD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Monk);
}
