// DARK BLOOD - gameplay module.
#pragma once

#include "CoreMinimal.h"

DARKBLOOD_API DECLARE_LOG_CATEGORY_EXTERN(LogDarkBlood, Log, All);
DARKBLOOD_API DECLARE_LOG_CATEGORY_EXTERN(LogDBSave, Log, All);
DARKBLOOD_API DECLARE_LOG_CATEGORY_EXTERN(LogDBQuest, Log, All);
DARKBLOOD_API DECLARE_LOG_CATEGORY_EXTERN(LogDBWorld, Log, All);
