[/Script/Engine.InputSettings]
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent
bEnableMouseSmoothing=False
bCaptureMouseOnLaunch=True
DefaultViewportMouseCaptureMode=CapturePermanently_IncludingInitialMouseDown
; Opens the console (developer commands DB*) on German keyboards too.
+ConsoleKeys=Tilde
+ConsoleKeys=Caret
